General:
  ConfigurationVersion: 2
  MinRefineryVersion: v2.0
Network:
  ListenAddr: "0.0.0.0:8080"
  PeerListenAddr: "0.0.0.0:8081"
GRPCServerParameters:
  Enabled: true
  ListenAddr: "0.0.0.0:9090"
RefineryTelemetry:
  AddRuleReasonToTrace: true
  AddSpanCountToRoot: true
  AddHostMetadataToTrace: true
Debugging:
  AdditionalErrorFields:
    - service.name
    - trace.span_id
    - trace.parent_id
    - trace.trace_id
Logger:
  Type: stdout
  Level: warn
LegacyMetrics:
  Enabled: false
OTelMetrics:
  Enabled: false
