#!/bin/sh

# Run to start the whole system up, 5 services (one is nginx)
# `./run``
# Or, run with a parameter service name (from docker-compose) to restart just that service
# `./run otel-collector`

if ! docker compose up -d "$@"; then
  echo ""
  echo "Failed to start services!"
  exit 1
fi

echo ""
echo "###############"
echo "Services started successfully!"
echo "###############"
echo ""
echo "To see the logs, run:"
echo "docker compose logs -f"
echo ""
echo "To stop the services, run:"
echo "./stop"
echo ""